global:
  cattle:
    url: https://rancher.example.com

registry: registry.rancher.com

# Integrates the app into the Rancher Dashboard sidebar
labels:
  catalog.cattle.io/cluster-repo-name: rancher-charts

rancher:
  enabled: true

manager:
  # Disabling ingress to avoid port 80 conflicts with ServiceLB
  ingress:
    enabled: false 
  svc:
    type: LoadBalancer

k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock

controller:
  replicas: 1
  prime:
    enabled: true
  pvc:
    enabled: true
    storageClassName: longhorn
  sso:
    enabled: true
  
  # This section fixes the "RBAC Disabled" error by forcing NeuVector 
  # to trust the Rancher platform for authentication.
  configmap:
    enabled: true
    data:
      sysinitcfg.yaml: |
        New_Service_Profile_Baseline: basic
        Auth_By_Platform: true
        Cluster_Name: k3s-security
        Scan_Config:
          Auto_Scan: true

cve:
  scanner:
    enabled: true
    replicas: 1


